
spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
      use.latest.version: true # this is needed for schema reference to work
      auto.register.schemas: false # this is needed for schema reference to workso that the name of the subject will be derived from record name ie, org.maziz.something
      specific.avro.reader: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
        use.latest.version: true # this is needed for schema reference to work
        auto.register.schemas: false # this i
        specific.avro.reader: true
server:
  port: 8079